.PP
Exponencial Curves

.EQ
 y = A times common ratio sup x
.EN

For another way to describe an exponencial 
curves, we might say. If the absolute value 
of the common ratio is greater than 1, 
then we have exponencial growth. 
And if the absolute value of common ratio is less that 1 we're then dealing with decay


.PP
Formula

- a and k are constants and T represents the time constant-the rate of decay
- e, the base of the natural logarithms

.EQ
x = ae sup -k/t
.EN


